# export LANG=ja_JP.UTF-8
# export TZ=Asia/Tokyo
# export GOROOT=/usr/local/go
# export GOPATH=$HOME/gohome
# export GOBIN=/usr/local/go/bin
# export GOHOME=$HOME/gohome
# export PATH=$PATH:/usr/local/go/bin
# export LD_LIBRARY_PATH=./
# export M2_HOME=/opt/maven
# export PATH=${M2_HOME}/bin:${PATH}
# export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
